<h1>0x05. Python - Exceptions</h1>
<ul>
<li><b>0-safe_print_list.py</b> - a function that prints x elements of a list</li>
<li><b>1-safe_print_integer.py</b> - a function that prints an integer with "{:d}".format()</li>
<li><b>2-safe_print_list_integers.py</b> - a function that prints the first x elements of a list and only integers</li>
<li><b>3-safe_print_division.py</b> - a function that divides 2 integers and prints the result</li>
<li><b>4-list_division.py</b> - a function that divides element by element 2 lists</li>
<li><b>5-raise_exception.py</b> - a function that raises a type exception</li>
<li><b>6-raise_exception_msg.py</b> - a function that raises a name exception with a message</li>
<li><b>100-safe_print_integer_err.py</b> - a function that executes a function safely</li>
<li><b>101-safe_function.py</b> - a function that divides 2 integers and prints the result</li>
<li><b>103-python.c</b> - the Python function def magic_calculation(a, b): that does exactly the same as the following Python bytecode</li>
</ul>
